# Generated by Django 4.1 on 2022-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchasesData', '0003_purchase_cashless_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_manufacturer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
