# Generated by Django 4.0.6 on 2022-08-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('taxpayer_name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(default=None, max_length=50)),
                ('is_manufacturer', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='store_address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='FIN',
            field=models.CharField(default='FIN_UNKNOWN', max_length=7, unique=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='purchases_data.store'),
        ),
    ]
