# Generated by Django 4.0.6 on 2022-07-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_data', '0003_purchase_alter_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchases_data.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchases_data.purchase')),
            ],
        ),
    ]
